export enum parameters {
  // describes the available parameters for each event
  CATEGORY = 'CATEGORY',
  TARGET = 'TARGET',
  LABEL = 'LABEL',
  STATUS = 'STATUS',
  TYPE = 'TYPE',
  RESULT = 'RESULT'
}

export enum category {
  // broadest category for events
  STATE = 'STATE',
  VALUE = 'VALUE',
  RENDER = 'RENDER',
  REQUEST = 'REQUEST',
  ACTION = 'ACTION'
}

export enum target {
  // describes who the event is about or from
  USER = 'USER',
  CLIENT = 'CLIENT',
  ADMIN = 'ADMIN',
  UI = 'UI',
  APP = 'APP',
  SHARE_EXTENSION = 'SHARE_EXTENSION',
  SEARCH = 'SEARCH'
}

export enum status {
  // describes the status or stage of the event
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BACKGROUND = 'BACKGROUND',
  LAUNCHED = 'LAUNCHED',
  LOADING = 'LOADING',
  SUCCESS = 'SUCCESS',
  FAIL = 'FAIL',
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT',
  START = 'START',
  CANCEL = 'CANCEL',
  ERROR = 'ERROR',
  DISMISS = 'DISMISS',
  OK = 'OK',
  STOP = 'STOP'
}

export enum type {
  // general event descriptor
  SWIPE = 'SWIPE',
  PRESS = 'PRESS',
  LONG_PRESS = 'LONG_PRESS'
}

export type result = number | string;

export enum label {
  // most descriptive name of an event
  ADDS_COUNT = 'addsCount',
  COMMENTS_COUNT = 'commentsCount',
  DONESCOUNT = 'donesCount',
  FRIENDS_COUNT = 'friendsCount',
  LIKES_COUNT = 'likesCount',
  MENTIONS_COUNT = 'mentionsCount',
  SHARES_COUNT = 'sharesCount',
  UNREAD_NOTIFICATIONS_COUNT = 'unreadNotificationsCount',

  // Requests
  FACEBOOK_LOGIN = 'FACEBOOK_LOGIN',

  // States
  APP_LAUNCHED = 'APP_LAUNCHED',
  SHARE_EXTENSION_LAUNCHED = 'SHARE_EXTENSION_LAUNCHED',
  APP_STATE_ACTIVE = 'APP_STATE_ACTIVE',
  APP_STATE_BACKGROUND = 'APP_STATE_BACKGROUND',
  SCREEN_LOADING = 'SCREEN_LOADING',
  ONBOARDING_LOADING = 'ONBOARDING_LOADING',
  COMMENTS_LOADING = 'COMMENTS_LOADING',
  SIGN_OUT = 'SIGN_OUT',

  // Actions
  PAGINATION = 'PAGINATION',
  REFRESH = 'REFRESH',
  SEND_FEEDBACK = 'SEND_FEEDBACK',
  SEND_DOWNLOAD_INVITE = 'SEND_DOWNLOAD_INVITE',
  SEND_POST_INVITE = 'SEND_POST_INVITE',
  NOTIFICATION_CARD = 'NOTIFICATION_CARD',
  FIND_FRIENDS_BUTTON = 'FIND_FRIENDS_BUTTON',
  VIEW_PENDING_FRIEND_REQEUSTS = 'VIEW_PENDING_FRIEND_REQEUSTS',
  COMING_SOON = 'COMING_SOON',
  SUGGESTED_FRIENDS_FACEBOOK_CONNECT = 'SUGGESTED_FRIENDS_FACEBOOK_CONNECT',
  TYPING = 'TYPING',
  PRIMARY_BUTTON = 'PRIMARY_BUTTON',
  SECONDARY_BUTTON = 'SECONDARY_BUTTON',
  FACEBOOK_LOGIN_BUTTON = 'FACEBOOK_LOGIN_BUTTON',

  // Renders
  SHARES_LIST = 'SHARES_LIST',
  ADDS_LIST = 'ADDS_LIST',
  DONES_LIST = 'DONES_LIST',
  COMMENTS_LIST = 'COMMENTS_LIST',
  INTRO_VIEW = 'INTRO_VIEW',

  // Friending
  // regex: (SEND_FRIEND_REQUEST|ACCEPT_FRIEND_REQUEST|REJECT_FRIEND_REQUEST|DELETE_FRIEND_REQUEST|REMOVE_A_FRIEND)
  SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST',
  ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST',
  REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST',
  DELETE_FRIEND_REQUEST = 'DELETE_FRIEND_REQUEST',
  REMOVE_A_FRIEND = 'REMOVE_A_FRIEND',
  AWAITING_RECIPIENT_ACCEPTANCE = 'AWAITING_RECIPIENT_ACCEPTANCE',

  USER_AVATAR = 'USER_AVATAR',

  // Shayring
  // regex: (START_SHARE|CONFIRM_SHARE|CANCEL_SHARE|TOGGLE_ALL_FRIENDS|TOGGLE_FRIEND|INVITE_FRIEND)
  SHAYR = 'SHAYR',
  TOGGLE_ALL_FRIENDS = 'TOGGLE_ALL_FRIENDS',
  TOGGLE_FRIEND = 'TOGGLE_FRIEND',
  INVITE_FRIEND = 'INVITE_FRIEND',

  // Post
  // regex: (ADD_TO_LIST|REMOVE_ADD|FRIENDS_COUNT|MARK_AS_DONE|REMOVE_DONE|COMMENT)
  POST_CARD = 'POST_CARD',
  ADD_TO_LIST = 'ADD_TO_LIST',
  REMOVE_ADD = 'REMOVE_ADD',
  MARK_AS_DONE = 'MARK_AS_DONE',
  REMOVE_DONE = 'REMOVE_DONE',
  COMMENT = 'COMMENT'
}
