install! 'cocoapods', :deterministic_uuids => false
platform :ios, '11.0'

def shared_pods
  pod 'Firebase/Core', '~>5.6.0'
  pod 'Firebase/Auth', '~>5.6.0'
  pod 'Firebase/Firestore', '~>5.6.0'
  pod 'Firebase/Messaging', '~>5.6.0'
  pod 'Fabric', '~>1.7.5'
  pod 'Crashlytics', '~>3.10.4'
end

target 'shayr' do
  shared_pods
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

target 'ShareExtension' do
  shared_pods
end
