# Every time you run fastlane, use `bundle exec fastlane [lane]`
# On your CI, add `[sudo] bundle install` as your first build step
# To update fastlane, just run `[sudo] bundle update fastlane`

fastlane_version '2.53.1'
require 'dotenv/load'


before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do

  desc 'fetch certificates and provisioning profiles'
  lane :certificates do
    register_devices(
      devices_file: './devices.txt'
    )
    match(
      type: 'development',
      app_identifier: [
          'com.daviswhitehead.shayr.ios',
          'com.daviswhitehead.shayr.ios.ShareExtension'
        ],
        readonly: true,
        force_for_new_devices: true
      )
    match(
      type: 'appstore',
      app_identifier: [
          'com.daviswhitehead.shayr.ios',
          'com.daviswhitehead.shayr.ios.ShareExtension'
        ],
        readonly: true,
        force_for_new_devices: true
      )
  end

  desc 'build ios application'
  private_lane :build do
    certificates
    increment_build_number(
      xcodeproj: './ios/shayr.workspace'
    )
    gym(
      scheme: 'shayr',
      workspace: './ios/shayr.workspace'
    )
  end

  desc 'ship a beta'
  lane :beta do
    build
    crashlytics(
      api_token: ENV['FABRIC_API_KEY'],
      build_secret: ENV['FABRIC_BUILD_SECRET']
    )
    commit_version_bump(
      message: 'bump build',
      xcodeproj: './ios/name.xcodeproj'
    )
    push_to_git_remote
  end
end

platform :android do
  # Android Lanes
end
